apiVersion: sources.knative.dev/v1beta1
kind: SinkBinding
metadata:
  name: bind-@@name@@
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: @@name@@

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default