apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: @@name@@
spec:
  broker: default
  filter:
    attributes:
      type: @@trigger@@
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: @@servicename@@
